services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla-istanbul
    ports:
      - "8002:8002"
    volumes:
      - ./valhalla-data:/custom_files
    environment:
      - tile_urls=https://download.geofabrik.de/europe/turkey-latest.osm.pbf
      - serve_tiles=True
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
    restart: unless-stopped
